### ISSUE TITLE
example をビルドすると text layer に日本語が出てこない？

### ISSUE THREAD

**Issue by ayato-p** [azu/pdf.js-controller#2]
面白そうだなと思って clone して example を README の手順に沿ってビルドしたんですが、表示したときに日本語が全て落ちてしまっているようで表示されませんでした。
僕の環境固有の問題なのか判断がつかないので issue にあげさせてもらいました。一応環境は下の通りです。

```
λ uname -a
Linux ubuntu 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

λ firefox -version
Mozilla Firefox 47.0

λ node --version
v6.2.2

λ npm version
{ npm: '3.9.5',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.2',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }
```

**Comment by azu** [comment]
おそらく XHRが `file://`だと上手く動かないからだと思われます。
(ChromeやFirefoなら、おそらくコンソールにエラーが出ていると思います。)

サンプルを動かすには `http://localhost` などの https? 下でhtmlを開く必要があります。
サンプルの方にローカルサーバを含める更新をしたので、お試しください。

```
git pull
npm install
npm start
open http://localhost:9080
```

**Comment by ayato-p** [comment]
対応ありがとうございます。確認できました。確かにローカルサーバーをたてずに、 `firefox index.html` として開いていました。
(FireFox でコンソール開きながら確認していたんですが、エラーの類は出力されていませんでした)
